{
  inputs,
  ...
}:
{
  imports = [
    # keep-sorted start
    ./acme.nix
    ./bulwark-webmail.nix
    ./caddy-common.nix
    ./caddy-hosts.nix
    ./common.nix
    ./david.nix
    ./desktop.nix
    ./fingerprint.nix
    ./fmd-server.nix
    ./git/nixos.nix
    ./gnome.nix
    ./hardware.nix
    ./itgmania.nix
    ./nixpkgs-config.nix
    ./overlays.nix
    ./packages-common.nix
    ./packages-desktop.nix
    ./plasma-bigscreen.nix
    ./plasma.nix
    ./popt/nixos.nix
    ./secureboot.nix
    ./support-vpn.nix
    ./users.nix
    ./vars.nix
    ./virtualization.nix
    ./vr.nix
    ./zsh/nixos
    inputs.disko.nixosModules.disko
    inputs.home-manager.nixosModules.home-manager
    inputs.nix-index-database.nixosModules.default
    inputs.sops-nix.nixosModules.sops
    # keep-sorted end
  ];
}
