{ pkgs, inputs, ... }:
let
  itgPacks = inputs.itgpacks.itgPacks.${pkgs.stdenv.hostPlatform.system};
in
{
  programs.itgmania = {
    enable = true;
    audioDevice = "alsa_output.pci-0000_0b_00.4.analog-stereo";
    extraPackages =
      (with pkgs.itgmaniaPackages; [ zmod-simply-love ])
      ++ (with itgPacks; [
        # keep-sorted start
        _15gays1pack
        _15gays2pack
        _5guys1pack
        _7guys1pack
        _9guys1pack
        adults-only
        altruism
        anime-extravaganza-1
        anime-extravaganza-2
        anime-extravaganza-3
        anime-extravaganza-4
        anime-extravaganza-5
        anime-music-pack-3
        anime-music-pack-4
        anime-stamina-sessions-for-the-energetically-slow
        another-tracks
        anthem-series-the-boys
        axor
        azvws-mini-pack-vol-2-advanced
        bangers-only-2
        barber-cuts-2
        barber-cuts-3
        bass-tester-extreme
        bass-tester-extreme-2
        bass-tester-extreme-3
        beat-flow
        better-days
        bite-sized-bangers-2
        blue-arrow-project
        blue-arrow-project-1-5
        blue-arrow-project-2
        blue-arrow-project-3
        bracket-spectrum-2
        braedens-technicality-3
        braedens-technicality-4
        brainrot-2
        brainrot-3-chinese-edition
        cafe-cursed-3
        camellia-mix
        cookies-cookies
        coretech
        cringle-desolation
        dance-party-wawa
        dancedancerevolution-2013-ac-japan
        dancedancerevolution-2014-ac-japan
        dancedancerevolution-a-ac-international
        dancedancerevolution-a20-ac-international
        dancedancerevolution-a20-plus-ac-international
        dancedancerevolution-a3-ac-international
        dancedancerevolution-world-ac-international
        dancedancerevolution-x3-vs-2ndmix-ac-japan
        dasquids-easy-quads
        deep-in-the-heart
        delta-megadump
        diamonds-in-the-rough-i
        dimobetes-24-sightread-pack
        dimocracy
        dimocracy-2021-second-term
        dimos-vi-selifmis
        dimos-vii-selifmis
        drillbot-hitech-v2
        drillbot-lotech
        east-coast-stamina-4
        egg-carton
        egg-carton-2
        egg-carton-3
        egg-carton-4
        eventual-ascension-5
        everlasting-memories
        favorites-2026-january
        fearmix-2023
        fietsemaker-dump-1
        fietsemaker-dump-2
        fietsemaker-dump-3
        fietsemaker-dump-4
        footswitch-spectrum
        forcednatures-misc
        forcednatures-otoge-fusion
        frumbletek
        girlpocalypse-2023-endurance
        girlpocalypse-2023-speed
        girlpocalypse-2023-stamina
        girlpocalypse-2023-timing
        girlpocalypse-world-2025-apprentice
        girlpocalypse-world-2025-endurance
        girlpocalypse-world-2025-speed
        girlpocalypse-world-2025-stamina
        girlpocalypse-world-2025-super-speed
        global-namespace
        global-namespace-2
        global-namespace-3
        global-namespace-callback
        global-namespace-hello-world
        gpops-pack-of-original-pad-sims-iv
        groove-house
        hardstyle-goes-hard
        headbangers-2
        high-chance-of-tech
        highflyers-tech-nically-terrifying-2
        highflyers-tech-trails-4
        horniest-pack-in-the-world
        huberts-hypertension
        in-the-groove
        in-the-groove-2
        in-the-groove-redux
        itg-rhythm-is-just-a-step-away
        itgmaker
        itl-online-2024
        itl-online-2024-unlocks
        itl-online-2025
        itl-online-2025-unlocks
        itl-online-2026
        itl-online-2026-unlocks
        jynx-does-streaming
        k-pop-demon-hunters
        k-rhythm
        kacpi-is-underjoyed
        kiwi
        kommunism
        koreyja
        koreyja-2
        koreyja-3
        koreyja-3-5
        kurren-nutpack
        lama-pack-2023
        legendz
        liseks-legacy
        lisia-nora-community-simfiles
        lisia-nora-community-simfiles-2
        lobster-roll
        manor-house-anthems
        maractus-package-2
        mawaru-collection
        maxx-simz-1
        maxx-simz-2
        minecraft-vol-1
        mungyodance-2
        mungyodance-3
        music-of-mythology
        nothin-but-nines
        notice-me-benpai
        notice-me-benpai-2
        ocean-eyes
        oh-henry-mad-stamina
        orcustrated-anomalies
        paczka-ziemniaczka
        piece-of-cake
        piece-of-cake-2
        piece-of-cake-3
        piece-of-cake-4
        piece-of-cake-5
        piece-of-cake-6
        piece-of-cake-7
        piece-of-cake-8
        precure-pad-pack-all-stars-dancing
        puyosimfile-1
        recyclables
        recycle-bin
        rhythm-rebellion
        rrw03-bring-the-sea-to-you
        scrypts-fruit-platter
        scrypts-pocket-lint
        sefirots-simfiles-5
        sharpnelshortz
        sharpnelstreamz-v1
        sharpnelstreamz-v2
        shpadoinkles-techsterity-3
        simfile-pl
        slav-streamz
        slav-streamz-appendix
        snaps-burfus-bonanza-2
        soraes-stax-2
        state-of-trance
        streamaniax
        studio-24
        tachyon-eta
        takbook-air
        tech-bit-adventures-3
        tech-bit-adventures-4
        tech-bit-adventures-5
        tevs-new-pack-of-simfiles-1
        tevs-new-pack-of-simfiles-2
        the-abyss-of-despair
        the-ace-of-charts
        theoretical-zektbach
        total-chaos
        tres
        ultra-party-mixtapes
        undertale
        vocaloid-project-pad-pack
        vocaloid-project-pad-pack-2nd
        vocaloid-project-pad-pack-3rd
        vocaloid-project-pad-pack-4th
        vocaloid-project-pad-pack-5th
        wafles-tech-frenzy
        whatsacc
        xmod-spectrum
        zibs-hip-hop
        # keep-sorted end
      ]);
  };
}
