adguardhome:
    pass: ENC[AES256_GCM,data:+9XD/MCF0s+cBmh3a2gaz3DMnjRPysNWTZm1X0wlppqRpaqvzpIeo2zz537AddBfzVH1+/bYb7NM4v82,iv:n9Wp7VVl34yK4l1xe6S3QhgnG8SlH8Au15LKP/jn0cA=,tag:I1k69hrW0rTLXcpwvfzFcw==,type:str]
caddy:
    basicauth: ENC[AES256_GCM,data:pSMGyG7iAPXw8TWcr5VxyK/cYyFL7pPL9qGxMVQZey75Pk/vYRegHKDynVWMK/7RotncGITZC09L8QsBNjrTFfBT,iv:qh7Y2UPoRpCTpKN4nvBsv88yjJTXb3BowlixZpQQ+xg=,tag:QxEcE+Oz7cwx1cUMZ3a5WQ==,type:str]
esphome:
    env: ENC[AES256_GCM,data:nLtIOQ8RdjnyaPFP0ekpNQHM5SJq5HnMtUsYjMhW19+3g+cpbd8j2OO20cvHReLlv222PumuPQb+,iv:WAPdS1C7M0p6RGawYQH82gOflZQRUTzjbmKuw6jIFlQ=,tag:YuXKjOgI0oqrEcJuCvX5sA==,type:str]
firefox:
    basicauth: ENC[AES256_GCM,data:gWRSysHUEQa9LfPvh6IbUTfOJgDCics3UJnmhdG070TSf/skuUji/Gse8mBRFlobDT1eJb1gf8tmDWJIc6Vj8coz,iv:Rl6OYH0ch1EhVATcLc2xAG4pbUXGf92V+uQ+V44K5Gk=,tag:LFzlrHJVG1ENrkTNNzIm6g==,type:str]
immich:
    smtppass: ENC[AES256_GCM,data:dVjUwe4TV/grjAQ1kGgJMkRYq29cAUTBGnrDxHvvmrI=,iv:dgEz7JLLl1wQ2RkahflnCNnpiR3AIxtdxASgPR7xUxM=,tag:qrjiwZTIkEjohJ+zH5VOVQ==,type:str]
openvscode-server:
    basicauth: ENC[AES256_GCM,data:yMaNmSBq6Me12UM27rArXF/sYvSz/TVbWniIOPbO7CMnOOiilQjdQshj1Zx9xztod3HKWqxd1aLHwHz/kLugBMoW,iv:F3VRjrcxCg2u/jfw8poPfLMdK41kL14S88JXoS3jUOw=,tag:Podwtvm8WZxWKjGV5K34sg==,type:str]
    token: ENC[AES256_GCM,data:TbKg5gTF+aev+Itw6W01yTeAKKB2AMpAQuEPwaNySX4=,iv:N112gkATENF4v94Q6u/IeSLWxZdZqReL7mt0qglJZ9k=,tag:I6q+Mou387ywFHTJzhzBuw==,type:str]
mollysocket:
    env: ENC[AES256_GCM,data:zLeeNo4cyieYFMeCqONfvi/e1Sh/TWsbBx6VKkWl+TiRnCDom0OOHld7kjDEqALdhT5KtJ8m5CMeNztBXtqpE2Ua+qYokMjl2WgFibNo3un+GikreUGlUqsa7Gjq7pgxLNV7x/X17ytzk56XSFqoxxVeSGBvGR4hjn1USotT6Q==,iv:h1Wg5wOxmkE9vHt2k4nbjDHzoBORyLKOKVRDKHXwVns=,tag:+Cka/RasM3XOlpXpGpVIzw==,type:str]
nextcloud:
    pass: ENC[AES256_GCM,data:AC8ccWa9UbUPdlUnEV9TjKUdlOcywL3YmScU2b9JT/o=,iv:uAIgHLpNgiNOvLfNnuwibBGB/U8KFIRA6Sl9XdgB1+s=,tag:+xPFlbXbulXViTDQZlaxhQ==,type:str]
    smtppass: ENC[AES256_GCM,data:Sba3jz5tfxNGmk+Hlv2REABDNwY1WUo3RCyeVaAXs6Y=,iv:69VdLxQsbjuhJimb1lJEior/80koE/rx+sAyVavCoQw=,tag:7f7az10OKGeDzretyGKnbg==,type:str]
ntfy-sh:
    env: ENC[AES256_GCM,data:PS1b32ygWmdObLeuyUn8fJhNRqCNRR2YXKArJTTGqXulDXHLyDvo9mdwFXNG5cmqoPB2gp2dCEuy55iEjzzA2DgbpeY+7uKFJeYjUit70AGl0kISlv2XiB+j94jbHBUTClSIRQZqTgyQkUHocnb4phEaROZWwdgvC4acn9jofrhH0po71KAaM7naSAHJJPHuJlANVDK29+kCdGskHbP+V4jwVBg8MLJ8mDZIhEQp6osyNaSLa/Bn,iv:ZJdHCLbxOmRVkyJ/Dk1ZX+E+C6jtlyO8L2wc9w0SP9I=,tag:tACM7LyAbB3Lc8f7eTGxuw==,type:str]
paperless:
    env: ENC[AES256_GCM,data:+o+E2doTyZJ7pyLHoCacSO1cPlpv3EcAucZL5EqWlkz9FcAsRfJOUtVJi+B5v06q/0CZyqlEu4eVJ3OcFzqf,iv:DV+kDAOYqxSZf+ZmAY8MvwyYpEFC0bYZHFBiGP6TshI=,tag:DP5XFBao08vC38y9ati+5g==,type:str]
    pass: ENC[AES256_GCM,data:FU2dwQvZTrgpqfHwIou+frwRWBIvcbPVVgQu/mdn6xg=,iv:nmUHCR92SSMRceH51Ve7FZDgpo89XppFvgP1F8fA9dc=,tag:+2qdbhsBe8zyUeqMyhhSFg==,type:str]
pdns:
    apikey: ENC[AES256_GCM,data:QkOpE1cOGciDAnpth7YgkUOw+bK1zrB2pf17R1mWMMUmaT7Y7qAjZaDswApuyaBAb5WQE2TaCNxBnyaw,iv:6/fBkU7cmWUCi9I39bCDtyiHE4vUiagmmeMtdR8gQ80=,tag:0jm80RUl3E6XlfbWuV6Xwg==,type:str]
phonetrack-notify:
    token: ENC[AES256_GCM,data:r1iVWHJisLKVep8RACdj17vN73g3GBmUBeH/8u8Ezi++s2MhUnJmisGpq6kN1X28ki4ul46CefeAcEXBPAtuMKBioO+LtjyvncgunHS+yLgLn2HHElcbI88mC4aoDjmz9zSJYd87pUkirZYi+e6znTtW89AMB5X0q2K41uagVNA5Js++RvKweFF8aPZl0yE10EfyY8fZT7XfVvdPmwuqQl2LhjCvteUkQw656UghlbAG4yVnNlOf,iv:R+/UAVcNRzoEaXYXpMZVEER8Q6HUgLv4ydcU0bdQBog=,tag:WtJERhq0WvLGsodZy3HS5A==,type:str]
samsung-grab:
    url: ENC[AES256_GCM,data:3cVfWAXA0IBqmNN7qqr74ngAeabrIYqDJ/VmnlgvxgnpoJE/9ZdQimN17T9bp5vm1I1ecM0HTAzTJlhA/O/jZQ==,iv:1izw1nVcoNe/5m/asK352qnQXVPH9Eej+33+7bls4LE=,tag:tLU9v8Ih+Gx9M88woLm7vA==,type:str]
samsung-update-bot:
    token: ENC[AES256_GCM,data:81/hzZ/F1V+Eb3plk5b3y3gxbwYFMexNRB1dltQit9AIOzhCVm81flGxmQZYnA==,iv:KsoB9LiGMJqzUjvIwvMKQy5fICUiKL9uPo/p9KJ8OK8=,tag:MJGOzT1mhbDJ8jax1stGBQ==,type:str]
sshwifty:
    basicauth: ENC[AES256_GCM,data:ZsShOPyqS7o7C9TJjud1n8khAtXDxB7y1zbwt8WTOlvIxoJzwL3sVvyAeVYYj+JRTi6TL4fnHmfKUzD/3pDW95G9,iv:1n3y8JLskp3zMjvGAQtAsiY+7+cnIF3+l52N0DM14KY=,tag:F5bIc1cskp29d2wvkV5bhA==,type:str]
    sharedkey: ENC[AES256_GCM,data:ef9kUcR7wQzMTQb6i2VshztztE6Ag7D+Oi3CkqQDpzc=,iv:8HPJ9kzTlANSlchrRG7r45iMhRV7IiC/KJlbm91IitI=,tag:dPNGvyxIck5hFDupp/r8Rw==,type:str]
stalwart:
    dbpass: ENC[AES256_GCM,data:iMTysvFqaxpSByEHJoCA3SAkkjnqXqwWaIUOxNwILw4=,iv:KFbWWyP+WeQ/AKi28dIZBoTFh2ZS34XauO9sGBDcOMo=,tag:bgyEnB/65dUVW7gGNYvNIw==,type:str]
    pass: ENC[AES256_GCM,data:kj96zjCvkoLzfGv3xhvZinCZK2Bx9EOlPhEpcJXoOkNgRWpsBG5dbukL1O6en+ggaBIoi5BKe9JbwBBbAGxZOdeKSGlKeD2NFwUoXffRDrv1SfjSOz7MWEv1L4kgx2BEynvrDLLJpfvfVA==,iv:VvTwFrW2l6gAPhAz2s5wGL4fzyS8xbFAK+PhVBZ+0Bk=,tag:9R+1FrIzUbjkGRSkcGusKw==,type:str]
users:
    david: ENC[AES256_GCM,data:3izz1jmQFOkfO5aTG3qEleY89Mu3iuVc0UW12HjcUUd/UPN6h+Ah9tYipiOS3PoS+vUGQpVQhKjzADTdNuJIc9ctX5Lp6mh4EQ==,iv:2fQ7QBtqmg6PXSfg+98O+iVY6NF/JudW0XnIbxV+S6o=,tag:Cs4DVqVFlbzdSO6UjLor+Q==,type:str]
vaultwarden:
    env: ENC[AES256_GCM,data:T9B1pEF+ryX7udv9TlDMdfzM79ppHkZuteFaoF9yX1BkiAHAafCGXFDpgmrEBKVgjH9yf33A/v3YBBzAX5i0iFYKXZ5SOzBTMqBaDBbkmz5sRGzVJAtLO1Flhxc+Y46jNhAysMlHKuvtTix1YqH5HL5RHyOHWDsrd+r7rvicRtOKM3T6N7NTLD9vR3PFh8VZMrtxY+EdoHvPfr7tNieaSryMb44eAszlaY5QTdcTUQ9SLyWlk4tw,iv:JAVYy55Q6P8IlorF3JOn9kOCWtK0ants8eLpImjzezQ=,tag:RS6846d3Qduzc+4rDGRc/A==,type:str]
wireguard:
    rpi5:
        #ENC[AES256_GCM,data:hlPF+JAhVy5S2rrhyAuxnFWBtLWCk8BAbNwxN9qc7HZe7v54rvhkVt+rwLLl5iPt/OfsDMMP8tbZ,iv:IBWHD9eRfr48oEXXSZDW8DaGbznRwk9zNyNUu8jh/mc=,tag:zdBWOYA5RZAmGmxAZnrBbQ==,type:comment]
        privkey: ENC[AES256_GCM,data:HdB4SirnJXhhXtG9uPLU+jWdirJQXANOlYDq1G6Isa+1DpaWRf+R+tRIaqc=,iv:gI5hzR0CAZrAAgFvtCHQO1iS6mrEftB7AXA0byjtf0s=,tag:Tih/M79HHWY/znG6zE9zLA==,type:str]
        #ENC[AES256_GCM,data:BIoKWM2OwAI=,iv:ntj8OUv9QpxzIXhlVpcZr1x0IYJ9MfBhCeIoWZCnNm0=,tag:oxAK8n32qhweleuPZx3N5Q==,type:comment]
        psk-1: ENC[AES256_GCM,data:2TpTqY9wjQouDAJ8dXC8YO7gcVRg/VVVOTwkzYhPjBjSR8qpCqJs4bvGgdM=,iv:NmSC96E63HKvblXqdMXn/hPv0S08DQhMU6biu3P2uzA=,tag:kAzRsahtkCTCFVHZuL8NXw==,type:str]
        #ENC[AES256_GCM,data:k4BanZGr,iv:sKh691Urz4l60ToSdJwPGi8GFdatCnjjf/CUW9ksFWM=,tag:pOelrpGYSBFNZnAYse+YXw==,type:comment]
        psk-2: ENC[AES256_GCM,data:CpC8bfCsMW6Z389yle+246Va0sNlhYIcDOJVx9bIG99r1b2rfmPvDwsD6xc=,iv:wQCWl7NSArBqkxk10L5HMyc4JzsaFd0++YqacrLhqJI=,tag:w6Uyrt6dy38lcAdnG/wWBQ==,type:str]
        #ENC[AES256_GCM,data:qIBnMA==,iv:5deBjD6b1hfg9gUJ93D3rVAjHRENJLHMkBpa6ptJpsk=,tag:UvaFxCAfVx/WW/7OWnLx0A==,type:comment]
        psk-3: ENC[AES256_GCM,data:bxXS4l6MXNeriRg3JungI8setBBYeM00UrS/HclP6eA1nAob8pMSBOOtfC0=,iv:6aM2W9dz5LReL1gPECeruiBuJ1bCAWl+y5RY+5JYETQ=,tag:0s/z01nDSag4L+NRvSSogQ==,type:str]
    support:
        #ENC[AES256_GCM,data:ndgK7zZgfxhv/Kp9R1595pZaUNQnV91edYjaXzbhpvX4IQAKCc7FVd/teiEf6odU7FYwB5bzPzwe,iv:hNrKIHdNxuuyWjvGyMY46f1PQLUN2RWArG2CiE8q3P0=,tag:x3UUqm59llSvmoWONLSy1g==,type:comment]
        privkey: ENC[AES256_GCM,data:7E6O2Z3Em/6t4l/JUbk0Wupb3WXjCib+o5+Yo+grKdPK/w4nMO5RIybNkYE=,iv:n2DApEfzR+SqTcyFSmaOkwR8hDBtneEhCklIksLrdEE=,tag:bJ/E1XE66Jf5A4YHv1Hlpg==,type:str]
        #ENC[AES256_GCM,data:XYq/6Jjn7H3XpX7Qig==,iv:ZHkU3bqugfyXmKxNiXQNgVc6D8oyBlr9GslJLxlGznU=,tag:6gS0aFN3L+D3zO0PB4gmaw==,type:comment]
        psk-1: ENC[AES256_GCM,data:m6aWCAVq7wkkmVao6NEfbKR2E8qV2KIFoymy2d4tt1q8UIwEwp79OfZ9PCI=,iv:/gGDf1hvtPCSEZ2XRbGTH72NEsRr7D2IHf1SDRK9mcA=,tag:DwNc2FcuUpRXT9ZlO/SRlA==,type:str]
        #ENC[AES256_GCM,data:S+T4GHapmXgRSxk=,iv:OnDaNPP+W8SxwL1M2KvIIPk7+Rbc7Wc+XvCQ9Y3CnQg=,tag:UNu/1KRQg3V94cdOrEVvsA==,type:comment]
        psk-2: ENC[AES256_GCM,data:kRSTQQdw2vcMN1h0DUxjcG2LfDbubD7zq7N6gxBW5axzDf5wXKbC629ajjM=,iv:WHXCJwwSI5D3+LGEh6k7sdYAHnls5WB7tA8R3DeY1Cs=,tag:k5fEnjaLEBvgzsUp9OeN0A==,type:str]
        #ENC[AES256_GCM,data:hWcGhvdNbA==,iv:QwG/qCOrvZ9cwfj8qF6DX1A8n+Nt+mnIQQIBQ3W2Wg4=,tag:F1yKvF1kicnLiU9aHJkhfw==,type:comment]
        psk-3: ENC[AES256_GCM,data:CXbMjqNCx5FhUlGTthFA4bkgCLUzjLd3VDYAbhdlISXjxUsw3Ps3Sv8FkDI=,iv:msuR7sLeoA6xTiPXLL4nYLW/ZjjXii4zvsBo5+Vc+t4=,tag:wqpo5BDUN/obMhhTWpjsdA==,type:str]
        #ENC[AES256_GCM,data:89oHmJ0YsA==,iv:AJEr9DW3v3ngh3TGJp3CqTaKiKQGtXsS6XEDv/0Ue8U=,tag:/Rp0ZnGxcDKdKCUi9lsUIQ==,type:comment]
        psk-4: ENC[AES256_GCM,data:j/z0niYhHIEvMkjH8rqNZoYU3Y4AHdTTfcbQBixZODtV0/EVYiyPTtWUGHc=,iv:dD2AUVnH8pUrZVkTX5U06eqDoi8vPSGsIJ8jJ98VmM0=,tag:f9UMLjebw1RlZkBxLvV1NQ==,type:str]
        #ENC[AES256_GCM,data:fXEsKc+qVw==,iv:3jTTGFtxKEDxlgugv/TDMUg6GzXdpY5d9ETfGZ8efaQ=,tag:oP+PHZSsgJdufxAbe7+NMw==,type:comment]
        psk-5: ENC[AES256_GCM,data:wxY829du1sClxIGWYV9XwoUXoVI2Qc2O0XzBAnCkqyr2DjIDtAgR+otH9so=,iv:7E3bUjdQ+bgW2VCUMMBnlSruGk03QHCNlZl1jwEybNc=,tag:gGHZ6kxmpbHsptBwHW+/Og==,type:str]
        #ENC[AES256_GCM,data:IHse3myg3mI/pfI=,iv:yQ4qwVuwU28FRaBtp9wyLvfSsig0+tfsb+jiQNKTnCQ=,tag:M1tn6Ce6yeAqhgMJDP/RlQ==,type:comment]
        psk-6: ENC[AES256_GCM,data:lySIAyrD0K68fSdDt9Mhvztss28POEqCxUOhfq74Jp/KFcekHFvpCgN7UCs=,iv:HN7wxOyaLN9nZbqKiNV8kWaIfY8CFTUCr0rkCz3Qpq0=,tag:bcUo5xwbCgeC0uzqzOfTkA==,type:str]
yuribot:
    env: ENC[AES256_GCM,data:466JSMB/xFzP9WnTAmn3d5MFae/+5wV2ZKI/dYuZfc7NXHyOxPQ51ZQJ5oJeeGbrRQmr0bY8HCqO,iv:hLMhdJtfVrQ1nH6ICSXMFXgvBuFBYsFPtbEC9KlT6xk=,tag:pMLzAvU+WtEMIcMUdeO2Qg==,type:str]
sops:
    age:
        - recipient: age1x67zpr06facj4aefzlx0d3nj56qpprm43jpvry8dxf9vn6u44dpqqj7k0f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TVhyVzk2QXpuSithMzhQ
            aWNiZmJ2RXZBajVHeXBRRjRwREJQTndNekVBCkZYVGtjcjdGTk9HYmhlTC9kcklk
            RDR6S3VaS3Njc3lFOWZ1VDg3ZWZUR1EKLS0tIHU5R0UzazBQc2hFbDdtcWlLbG05
            SkJnMHhXSXlodzdqWFdINHNNUlBHU1EKiUKspR24tqxXJdVWezkuAiFB844Z/Bo0
            Q1qLR0Rk/fyShG2ZxiT4Bwn7Zvc/SSloZ5fNkH8qNx2WxEn9uncV7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T06:47:29Z"
    mac: ENC[AES256_GCM,data:GjFZS9LsnP/tKD5pb8Rl4NZJAuys3NHtBGauZmvPGoyB87hTx1AKnlk70B8WsEB+O6hEYoVONr+b85f9NdsrreMGcVavJG8oPc1IbCgy5DptR1fh6VVK6jv6OxuDZV7Y7tY+Ivb6uI3xel0xASALoc8Ja1FzwcGdMHl6uNdFqKU=,iv:4XubYzvQ0RCaQtw/WnGbNKUOZl/j1hPnn2w8aRII2T0=,tag:plu6nA5ZPxz6hVR2kqpmfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
