adguardhome:
    pass: # `htpasswd -B -C 10 -n -b <USERNAME> <PASSWORD>`
esphome:
    env: |
        USERNAME=david
        PASSWORD= # Plain text
mollysocket:
    env: |
        MOLLY_ALLOWED_UUIDS=[""] # Signal Account UUID
        MOLLY_VAPID_PRIVKEY="" # `mollysocket vapid gen`
nextcloud:
    pass: # Plain text
    smtppass: # Plain text
pdns:
    apikey: # Plain text
samsung-update-bot:
    token: # Plain text
stalwart:
    dbpass: # Plain text
    pass: # `openssl passwd -6`
users:
    david: # `mkpasswd`
vaultwarden:
    env: |
        ADMIN_TOKEN='' # `vaultwarden hash`
        SMTP_PASSWORD='' # Plain text
wireguard:
    rpi5:
        privkey: # `wg genkey`
        psk-1: # `wg genpsk`
        psk-2: # `wg genpsk`
yuribot:
    env: TG_TOKEN='' # Plain text
