# Default password is "changeme"
adguardhome:
    pass: $2y$10$7Mlggxu3yNyXG5kDky4f2uVloFLbi/KwgddiO/CB6CSLZKTcGEf7O # `htpasswd -B -C 10 -n -b <USERNAME> <PASSWORD>`
esphome:
    env: |
        USERNAME=david
        PASSWORD=changeme # Plain text
mollysocket:
    env: |
        MOLLY_ALLOWED_UUIDS=["dbb7af5f-212a-4e39-8d5e-b05b9b6d24fa"] # Signal Account UUID
        MOLLY_VAPID_PRIVKEY="_FLWrhz10o_THnFrLdpetC1UkuQuJ1sozUaRTlN27sc" # `mollysocket vapid gen`
nextcloud:
    pass: changeme # Plain text
    smtppass: changeme # Plain text
pdns:
    apikey: changeme # Plain text
stalwart:
    dbpass: changeme # Plain text
    pass: $6$g2v4GcDrMG7IfRE0$wyC5qI6KXM2JHPSaMvZtCo8hJ/r0i.5mksjGmRb8ezy9bbHq1gi5UnBqF5q05TArwnoCJX/Y0Ht8EUl2XW1kd. # `openssl passwd -6`
users:
    david: $y$j9T$N1mbgO1iMLkWaHAoi9Isv1$UC5b9w.PffDRv0ycyAKsxhZYNaGb8o8zzRcBzzII620 # `mkpasswd`
vaultwarden:
    env: |
        ADMIN_TOKEN='$argon2id$v=19$m=65540,t=3,p=4$wQk/eawxLMb+3Po4DmEA3X7t53Lhrpv6oilmEJT8oZQ$y2vS/6HrcNOE7gnDW/tABBcXPqbaF+NY9h1lc4Y3KHA' # `vaultwarden hash`
        SMTP_PASSWORD=changeme # Plain text
